#!/bin/bash
if [[ "$(id -u)" -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit;
fi
if grep -q "xdebug" /etc/php/8.3/mods-available/xdebug.ini; then
    zenity --question --text='XDebug is enabled. Do you want to disable it?' && echo '' > /etc/php/8.3/mods-available/xdebug.ini
else
    zenity --question --text='XDebug is disabled. Do you want to enable it?' && cat /var/xdebug.ini > /etc/php/8.3/mods-available/xdebug.ini
fi
